name: build docker image and push to GCP artifact registry

# run on every push to main branch
on:
  push:
    branches: [ main ]

# europe-west6-docker.pkg.dev/gcp-testing-374311/gcp-dev-ops-test/gcp-dev-ops-test
env:
  PROJECT_ID: gcp-testing-374311
  GAR_LOCATION: europe-west6
  REPOSITORY: gcp-dev-ops-test
  IMAGE: gcp-dev-ops-test

jobs:
  login-build-push:
    name: Docker login, build, and push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 'Docker build'
      run: |-
        docker build -t $IMAGE:latest .
        docker tag $IMAGE:latest "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE" 
    
    - uses: 'docker/login-action@v1'
      name: 'Docker login'
      with:
        registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
        username: 'oauth2accesstoken'
        password: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

    - name: 'Docker push'
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE"